### ISSUE TITLE
Visualization for Class Shift

### ISSUE THREAD

**Issue by XufengGAO** [RenshengJi/C-CoTTA#1]
Hi authors, 

Thanks for your amazing work! 
Could you please tell me how to generate the visualisation plot of domain shift (the Fig.3 in paper)？If possible, could you please provide any code snippets for this part?

Thank you so much.

**Comment by RenshengJi** [comment]
Hello, thank you for your interest in our work. Unfortunately, I did not save that part of the code in the GitHub repository because it serves as auxiliary drawing functionality, so it is no longer accessible. However, I will explain how the image was obtained:
1. First, during the test-time adaptation process, we saved the features of each class from the source domain and the target domain.
2. Next, we performed t-SNE dimensionality reduction on these features (it is worth noting that, for fairness in comparison, the features from all methods were reduced together).
3. Finally, we used the reduced features to create the plot, where classes are represented by different colors, domains are represented by different opacities, and the shift direction of classes from the source domain to the target domain is indicated by arrows (with the starting and ending points of the arrows being the prototypes).
